'use strict';

// tests for saveBirthday
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('saveBirthday', '/src/create.js', 'saveUserBirthday');



describe('saveBirthday', () => {
  before((done) => {
    done();
  });


  it('Return statusCode must be 204 for create or update', () => {
    return wrapped.run({"pathParameters": {"id":"John"}, "body":"{\"birthday\":\"2000-12-26\"}" } ).then((response) => {
      //console.log(JSON.stringify(response));
      expect(response.statusCode).to.be.equal(204);
      
    });    
  });

  it('Return statusCode must be 400 for invalid date', () => {
    return wrapped.run({"pathParameters": {"id":"User1"}, "body":"{\"birthday\":\"2000-02-31\"}" } ).then((response) => {
      //console.log(JSON.stringify(response));
      expect(response.statusCode).to.be.equal(400);
      
    });
  });

});
